AllCops:
  Exclude:
    - 'db/schema.rb'
    - bin/*
  NewCops: disable

Documentation:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'app/routes/*.rb'

Lint/NonDeterministicRequireOrder:
  Enabled: false

MethodParameterName:
  Enabled: false

MethodLength: 
  Max: 20