version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'

  app:
    build: .
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    ports:
      - "4567:4567"
    entrypoint: /entrypoints/application.sh
    depends_on:
      - db
